{% set name = "tscv" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4934fcc9d5210d0bc4efcade76c195be2fb10bed82c827b05ac39953ef4dddc9

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - scikit-learn >=0.22
    - numpy

test:
  imports:
    - tscv
  requires:
    - pytest
    - python {{ python_min }}
  source_files:
    - tscv/tests
  commands:
    - pytest

about:
  home: https://github.com/WenjieZ/TSCV
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Time Series Cross-Validation -- an extension for scikit-learn
  description: |
    This repository is a scikit-learn extension for time series cross-validation.
    It introduces gaps between the training set and the test set,
    which mitigates the temporal dependence of time series and prevents information leakage.
  doc_url: https://tscv.readthedocs.io/en/latest/
  dev_url: https://github.com/WenjieZ/TSCV

extra:
  recipe-maintainers:
    - WenjieZ
